### ISSUE TITLE
Phasor threshold functions with manual and automatic 

### ISSUE THREAD

**Issue by schutyb** [napari-phasors/napari-phasors#18]
Create a threshold function for the intensity (dc) 

- [ ] One for manual threshold with the dc histogram 
- [ ] Apply automatic thresholding from skit image

**Comment by bruno-pannunzio** [comment]
Thresholding was implemented in #40. I leave the issue open for us to remember of the automatic thresholding to be implemented in the future.

**Comment by bruno-pannunzio** [comment]
I will close this issue as the automatic thresholding was raised instead in #64  as a separate issue.
