### ISSUE TITLE
Create a widget to calculate phasors

### ISSUE THREAD

**Issue by zoccoler** [napari-phasors/napari-phasors#2]
We should start by providing a function to calculate G, S and DC images.

If we don't want to load raw data to the viewer, I think we can do this in a couple ways:
- Write a reader function (check more info [here](https://napari.org/stable/plugins/guides.html#readers)) to read the raw data upon file opening and return summed intensity image, G, S and DC images already (while optionally saving them to disk)
- Write a widget function (similar to the one we discussed), but provide a field for file path (like [here with magicgui](https://pyapp-kit.github.io/magicgui/api/widgets/FileEdit/) or [example here with pyqt](https://www.tutorialspoint.com/pyqt/pyqt_qfiledialog_widget.htm)) and also return these same images

If you have other ideas, let's discuss

**Comment by zoccoler** [comment]
To Do:

- [ ] a widget to calculate phasors of raw data (optionally save DC, G and S as OME-TIFF, probably never used)
  - via Plugins menu
  - inputs
    - path to data
    - harmonics
    - channels
    - frames

- [ ] reader function to calculate phasors with default options

- [ ] a widget/reader to load these OME-TIFF
  - output
    - image layer with metadata containing Labels layer with table

**Comment by bruno-pannunzio** [comment]
Add 'scale' parameter to the layer from image metadata

**Comment by bruno-pannunzio** [comment]
Solved in #12. `Scale` parameter still not implemented, but #13 is were the issue was raised.
