### ISSUE TITLE
Renaming layer doesn't update Image layer in Plotter

### ISSUE THREAD

**Issue by bruno-pannunzio** [napari-phasors/napari-phasors#28]
When manually renaming a layer, the Combobox of the Image Layer in the Plotter doesn't update the name and when selecting the old name layer, the error `KeyError: 'old_name' is not in list.

**Comment by zoccoler** [comment]
Hi @bruno-pannunzio ,

I tried to reproduce this issue, and indeed the new name does not show up in the combobox if it was already plotted, but I did not get any error message. Please check below:

![napari_phasors_layer_renaming](https://github.com/user-attachments/assets/5963acf7-7279-45e9-84f1-920939e8f6fc)

In any case, a potential solution seems to be to connect somehow the `reset_layer_choices` method to `layer.events.name` from napari (check napari events [here](https://napari.org/stable/guides/events_reference.html#layer-events)
