### ISSUE TITLE
Add sample data

### ISSUE THREAD

**Issue by zoccoler** [napari-phasors/napari-phasors#3]
It would be good to add one or a few sample data to the plugin, so that we can actually test the other functions later and users can try them out as well.

This is explained [here](https://napari.org/stable/plugins/guides.html#sample-data)

**Comment by zoccoler** [comment]
Sample data can be found here: https://github.com/napari-phasors/napari-phasors/tree/main/src/napari_phasors/_tests/test_data

**Comment by zoccoler** [comment]
- [ ] decide where to upload these sample files below
- [ ] add calibration for `.fbd` file
- [ ] replace `.lsm` file for a better example with different cells
- [ ] add a new `.ptu` file (or a series of files, if 3D) with calibration

**Comment by bruno-pannunzio** [comment]
This issue was solved in #65
