### ISSUE TITLE
Possible bug with phasors location ?

### ISSUE THREAD

**Issue by zoccoler** [napari-phasors/napari-phasors#45]
Hi @bruno-pannunzio ,

I was testing to open some of the sample data and plot them. But it looks their location in the phasor is shifted, take a look for the test_file.ome.tif below:

![image](https://github.com/user-attachments/assets/7584d06b-0ae6-43ec-8f1f-af09e750b098)

Could it be lack of calibration or is there something wrong?

**Comment by bruno-pannunzio** [comment]
Hi @zoccoler! I believe that the ome.tiff in the 'test_data' is uncalibrated, thats why we see it outside of the semicircle. It might be a good idea to replace it with a calibrated one instead. I can modify it and upload the calibrated version. Although this made me check the calibration widget and it is not working as expected. So there is some bug that I have to find and fix.

**Comment by bruno-pannunzio** [comment]
The bug related to calibration was fixed in #46. As it was only a minor fix I already merged it.

**Comment by zoccoler** [comment]
Alright, but this also happens when I open the .fbd file, and even the .ptu looks a bit outside the circle. Are they also uncalibrated?

**Comment by bruno-pannunzio** [comment]
> Alright, but this also happens when I open the .fbd file, and even the .ptu looks a bit outside the circle. Are they also uncalibrated?

Exactly, all .fbd and .ptu files are raw uncalibrated. We can also include a file of reference for calibration, since we cannot modify this raw files to be calibrated (unless we export as OME.TIF).

**Comment by zoccoler** [comment]
I see, it makes sense.
If you happen to have a calibration image of those files, I would add them to the repository for completeness. They could be used as examples on how to use the calibration widget. If they don't exist, then no problem.

I still intend to make these files Sample Files that the user can just open from the napari File menu.

**Comment by bruno-pannunzio** [comment]
Excellent idea. I have the calibration file for the FBD file that I can upload. The PTU file was extracted from your hazelnut image, so I don't have the calibration, but we can work this out. I will add the FBD calibration file.

If you could add the Sample Files that would be great so I can see how it's done and then add the other files.

**Comment by zoccoler** [comment]
Alright, let me know when you add the calibration file. I will then add them as samples within the next weeks.
