### ISSUE TITLE
Remove x-axis, y-axis options, and Plot Type from Plotter

### ISSUE THREAD

**Issue by zoccoler** [napari-phasors/napari-phasors#8]

**Comment by bruno-pannunzio** [comment]
@zoccoler I was trying to run the plotter with the code you provided but run into this error:
    ```
self.canvas_widget.artists[ArtistType.SCATTER].color_indices_changed_signal.connect(self.update_manual_selection)
AttributeError: 'Scatter' object has no attribute 'color_indices_changed_signal'
```

I installed biaplotter via pip, could it be that the pip version is not the same as the one you are using and is causing the issue?

Sorry I commented in this issue which is not strictly related.

**Comment by zoccoler** [comment]
Hi @bruno-pannunzio ,

It seems indeed that this signal was not shipped in the first release, I am sorry for that. I made a new release, let me know if it works now and otherwise, please use the development version in the meantime.

**Comment by bruno-pannunzio** [comment]
That worked! Thanks Marcelo.

**Comment by zoccoler** [comment]
This below needs to be updated:
![image](https://github.com/napari-phasors/napari-phasors/assets/26173597/f9b9c957-2ddd-4005-8df4-2a4caad99457)
